### ISSUE TITLE
GoogleAds-IMA-iOS-SDK v3.1.0

### ISSUE THREAD

**Issue by dmorrow** [ooyala/ios-sdk-podspecs#11]
GoogleAds-IMA-iOS-SDK 3.1.0 does not load VAST tag correctly.  However, 3.0.b16 (as included in the [ios-sample-apps](https://github.com/ooyala/ios-sample-apps)) works correctly.  Please update or add a release note to indicate this.

**Comment by lental** [comment]
We have since updated, and now support 
3.2.1: https://github.com/ooyala/ios-sample-apps/blob/stable/vendor/GoogleIMA/GoogleInteractiveMediaAds-GoogleIMA3ForAdMob/VERSION
