### ISSUE TITLE
Add OoyalaSkinSDK-iOS

### ISSUE THREAD

**Issue by docterd** [ooyala/ios-sdk-podspecs#19]
It seems a Podspec for the Skin SDK is missing. Please add one.

**Comment by rcvrgs** [comment]
We are working on this. There are some problems with React native dependencies, that's why it's taking time.

**Comment by Mazyod** [comment]
+1 Would really love to have this

**Comment by javierugarte** [comment]
any solution?

**Comment by maxkupetskii** [comment]
@javierugarte 

It is not up to us to deliver RN libraries so Skin SDK should be downloaded separately.
Closing
